name: Run tests
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          python -m pip install -e .[dev]
      - name: Lint with flake8
        run: |
          flake8 schema_exporter --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 test --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 schema_exporter --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          flake8 test --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run mypy
        run: |
          mypy schema_exporter
      - name: Test with pytest
        run: |
          pytest
